name: Enhanced Whisparr for JPN

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: Whisparr/Whisparr
          ref: eros

      - name: Checkout patch repository
        uses: actions/checkout@v3
        with:
          repository: Teeeeemo/whisparr-patch
          path: patch

      - name: Apply patch
        run: git apply patch/fix-parser.patch

      - name: Debug DOCKERHUB_TOKEN secret
        env:
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "DEBUG: The DOCKERHUB_TOKEN is: $TOKEN"

  call:
    uses: Teeeeemo/build-workflow/.github/workflows/build-on-call.yml@master
    secrets: inherit

      # - name: Build Docker image
      #   run: |
      #     docker build -t whisparr-enhanced .

      # - name: Push to Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker tag whisparr-enhanced winzzzzz/whisparr-enhanced:latest
      #     docker push winzzzzz/whisparr-enhanced:latest
